/// <reference types="node" />
// Audio / subtitle tracks read from real file headers (fixtures generated by
// scripts/format-samples/audio-tracks.sh: synthetic ffmpeg / mkvmerge files, first 16 KiB kept).
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { audioVerdict, langCode, langFromTitle, pickAudioTrack, sniffMore, sniffTracks, type MediaTrack } from '../tracks';

const fx = (name: string) => new Uint8Array(readFileSync(new URL(`./fixtures/tracks/${name}`, import.meta.url)));
const audioOf = (tracks: MediaTrack[]) => tracks.filter((t) => t.kind === 'audio');

test('MKV MULTI with a French dub: Japanese default + "VF", forced and full French subtitles', () => {
  const { list, need } = sniffTracks(fx('multi-fr.mkv.head'));
  assert.equal(need, undefined);
  assert.ok(list?.complete);
  assert.equal(list!.container, 'mkv');
  const audio = audioOf(list!.tracks);
  assert.deepEqual(audio.map((t) => [t.lang, t.name, t.default]), [['ja', 'Japonais', true], ['fr', 'VF', false]]);
  const subs = list!.tracks.filter((t) => t.kind === 'sub');
  assert.deepEqual(subs.map((t) => [t.lang, t.forced]), [['fr', true], ['fr', false]]);
  assert.deepEqual(audioVerdict(audio), { langs: ['ja', 'fr'], conclusive: true });
  assert.equal(pickAudioTrack(audio, ['fr']), 1);
});

test('MKV "MULTI" without French: conclusive, no French track', () => {
  const { list } = sniffTracks(fx('multi-nofr.mkv.head'));
  const v = audioVerdict(audioOf(list!.tracks), list!.complete);
  assert.deepEqual(v, { langs: ['ja', 'en'], conclusive: true });
  assert.equal(pickAudioTrack(audioOf(list!.tracks), ['fr']), -1);
  assert.equal(pickAudioTrack(audioOf(list!.tracks), ['fr', 'en']), 1);
});

test('MKV untagged release with a French track, and a title-only track ("Français")', () => {
  const a = audioOf(sniffTracks(fx('untagged-fr.mkv.head')).list!.tracks);
  assert.deepEqual(a.map((t) => t.lang), ['fr']);
  const b = audioOf(sniffTracks(fx('title-only.mkv.head')).list!.tracks);
  assert.deepEqual(b.map((t) => t.lang), ['und', 'und']);
  assert.equal(pickAudioTrack(b, ['fr']), 1);
  assert.deepEqual(audioVerdict(b), { langs: ['ja', 'fr'], conclusive: true });
});

test('MKV with 3 MiB of font attachments before the clusters: the Tracks element is in the head', () => {
  const { list, need } = sniffTracks(fx('attachments.mkv.head'));
  assert.equal(need, undefined);
  assert.deepEqual(audioOf(list!.tracks).map((t) => [t.lang, t.name ?? null]), [['ja', 'Japonais'], ['fr', 'VF']]);
});

test('MP4 faststart: mdhd languages and handler names', () => {
  const { list } = sniffTracks(fx('multi-fr.mp4.head'));
  assert.equal(list!.container, 'mp4');
  assert.ok(list!.complete);
  assert.deepEqual(audioOf(list!.tracks).map((t) => [t.lang, t.name]), [['ja', 'Japonais'], ['fr', 'VF']]);
});

test('MP4 with its moov at the end: range to read, then the tracks', () => {
  const head = fx('nofr-moov-end.mp4.head');
  const first = sniffTracks(head);
  assert.equal(first.list, null);
  assert.ok(first.need && first.need.start === 102892);
  const more = sniffMore(head, fx('nofr-moov-end.mp4.moov'), first.need!.start);
  assert.deepEqual(audioOf(more.list!.tracks).map((t) => t.lang), ['ja', 'en']);
  assert.ok(more.list!.complete);
});

// ---------- synthetic Matroska: Tracks after a large element, found through the SeekHead ----------

const vsize = (n: number) => [0x01, 0, (n / 2 ** 40) & 0xff, (n / 2 ** 32) & 0xff, (n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff];
const idBytes = (id: number) => {
  const out: number[] = [];
  for (let v = id; v > 0; v = Math.floor(v / 256)) out.unshift(v & 0xff);
  return out;
};
const el = (id: number, payload: number[]) => [...idBytes(id), ...vsize(payload.length), ...payload];
const txt = (s: string) => [...new TextEncoder().encode(s)];

test('MKV: the SeekHead points at Tracks past a large element → follow-up range, then the tracks', () => {
  const tracks = el(0x1654ae6b, [
    ...el(0xae, [...el(0xd7, [1]), ...el(0x83, [2]), ...el(0x22b59c, txt('jpn'))]),
    ...el(0xae, [...el(0xd7, [2]), ...el(0x83, [2]), ...el(0x22b59c, txt('fre')), ...el(0x536e, txt('VF'))]),
  ]);
  const voidSize = 400 * 1024;
  // SeekHead with a fixed-size SeekPosition (filled once the layout is known).
  const seekHead = (pos: number) => el(0x114d9b74, el(0x4dbb, [...el(0x53ab, idBytes(0x1654ae6b)), ...el(0x53ac, [(pos >>> 24) & 0xff, (pos >>> 16) & 0xff, (pos >>> 8) & 0xff, pos & 0xff])]));
  const voidHeader = [0xec, ...vsize(voidSize)];
  const tracksPos = seekHead(0).length + voidHeader.length + voidSize;
  const ebml = el(0x1a45dfa3, el(0x4282, txt('matroska')));
  const segHeader = [0x18, 0x53, 0x80, 0x67, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff];
  const head = new Uint8Array([...ebml, ...segHeader, ...seekHead(tracksPos), ...voidHeader, ...new Array(1024).fill(0)]);
  const segData = ebml.length + segHeader.length;

  const first = sniffTracks(head);
  assert.equal(first.list, null);
  assert.equal(first.need?.start, segData + tracksPos);
  const more = sniffMore(head, new Uint8Array(tracks), first.need!.start);
  assert.deepEqual(audioOf(more.list!.tracks).map((t) => [t.lang, t.name ?? null]), [['ja', null], ['fr', 'VF']]);
});

test('MKV: no Language element means English by the spec, but proves nothing', () => {
  const tracks = el(0x1654ae6b, el(0xae, [...el(0xd7, [1]), ...el(0x83, [2])]));
  const ebml = el(0x1a45dfa3, el(0x4282, txt('matroska')));
  const head = new Uint8Array([...ebml, ...el(0x18538067, tracks)]);
  const audio = audioOf(sniffTracks(head).list!.tracks);
  assert.equal(audio[0].lang, 'en');
  assert.equal(audio[0].langImplicit, true);
  assert.deepEqual(audioVerdict(audio), { langs: [], conclusive: false });
});

test('a Tracks element cut by the end of the buffer: partial list + the rest to read', () => {
  const full = fx('multi-fr.mkv.head');
  // Cut inside the second audio TrackEntry.
  const cut = full.subarray(0, 600);
  const r = sniffTracks(cut);
  if (r.list) assert.equal(r.list.complete, false);
  assert.ok(r.need);
});

test('languages: tags and titles', () => {
  assert.equal(langCode('fre'), 'fr');
  assert.equal(langCode('fra'), 'fr');
  assert.equal(langCode('fr-CA'), 'fr');
  assert.equal(langCode('es-419'), 'es');
  assert.equal(langCode('und'), 'und');
  assert.equal(langCode(''), 'und');
  assert.equal(langFromTitle('VF'), 'fr');
  assert.equal(langFromTitle('VFQ (Québec)'), 'fr');
  assert.equal(langFromTitle('Français'), 'fr');
  assert.equal(langFromTitle('English Dub'), 'en');
  assert.equal(langFromTitle('Japonais (VO)'), 'ja');
  assert.equal(langFromTitle('Latino'), 'es');
  assert.equal(langFromTitle('Stereo'), null);
});

test('pickAudioTrack: player track lists (AVPlayer / mpv shapes)', () => {
  // AVPlayer: language tags.
  const av = [{ language: 'ja', label: 'Japonais' }, { language: 'fr', label: 'Français' }];
  assert.equal(pickAudioTrack(av, ['fr']), 1);
  // mpv: ISO 639-2 tags.
  const mpv = [{ lang: 'jpn', name: 'Japanese' }, { lang: 'eng', name: 'English' }, { lang: 'fre', name: 'French' }];
  assert.equal(pickAudioTrack(mpv, ['fr']), 2);
  assert.equal(pickAudioTrack(mpv, ['de', 'en']), 1);
  // Untagged tracks: the title decides.
  const titled = [{ language: 'und', label: 'Piste 1 - JAP' }, { language: 'und', label: 'Piste 2 - VFF' }];
  assert.equal(pickAudioTrack(titled, ['fr']), 1);
  // A tag beats a title elsewhere in the list.
  assert.equal(pickAudioTrack([{ language: 'und', label: 'VF' }, { language: 'fr', label: 'Track 2' }], ['fr']), 1);
  // Nothing in the language.
  assert.equal(pickAudioTrack([{ language: 'ja', label: 'Japanese' }], ['fr']), -1);
  // Unknown tracks: inconclusive (never a reason to drop a source).
  assert.deepEqual(audioVerdict([{ language: 'und', label: 'Piste 1' }]), { langs: [], conclusive: false });
});
